# Generated by Django 3.2 on 2021-05-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wod_date', models.DateField(verbose_name='WOD Date')),
                ('description', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WodExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.JSONField()),
                ('duration', models.IntegerField()),
                ('notes', models.TextField()),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.exercise')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.wod')),
            ],
        ),
    ]
