# Generated by Django 3.2 on 2021-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wodexercise',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wodexercise',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wodexercise',
            name='rounds',
            field=models.JSONField(null=True),
        ),
    ]
